apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-openresty-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    worker_processes auto;
    events {
      worker_connections 1024;
    }
    http {
      include       mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;

      server {
        listen 80;
        server_name localhost;

        location / {
          proxy_pass http://wordpress-service:80;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Lua scripts can be included here
        # include lua scripts if needed
      }
    }