apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-openresty.fullname" . }}
  labels:
    app: {{ include "nginx-openresty.name" . }}
    chart: {{ include "nginx-openresty.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "nginx-openresty.name" . }}
    release: {{ .Release.Name }}