apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  wordpressTitle: "My Development WordPress Site"
  wordpressUsername: "admin"
  wordpressPassword: "admin_password"
  wordpressEmail: "admin@example.com"
  wordpressDatabase: "wordpress_db"
  mysqlRootPassword: "root_password"
  mysqlUser: "wordpress_user"
  mysqlPassword: "user_password"
  mysqlDatabase: "wordpress_db"
  nginxHost: "dev.example.com"
  nginxPort: "80"
  persistence:
    enabled: true
    storageClass: "nfs"
    accessModes:
      - ReadWriteMany
    size: 10Gi
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  ingress:
    enabled: true
    path: /
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: dev.example.com
        paths:
          - /
    tls:
      - secretName: wordpress-tls
        hosts:
          - dev.example.com