apiVersion: v1
kind: PersistentVolume
metadata:
  name: readwrite-many-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /path/to/nfs
    server: nfs-server.example.com

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readwrite-many-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi