apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  labels:
    app: wordpress
data:
  wordpressUsername: admin
  wordpressPassword: password
  wordpressEmail: admin@example.com
  wordpressBlogName: My Blog
  mysqlRootPassword: rootpassword
  mysqlUser: wordpressuser
  mysqlPassword: wordpresspassword
  mysqlDatabase: wordpress
service:
  type: ClusterIP
  port: 80
  annotations: {}
persistence:
  enabled: true
  storageClass: "nfs"
  accessModes:
    - ReadWriteMany
  size: 10Gi
ingress:
  enabled: false
  hostname: wordpress.local
  path: /
  annotations: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}