apiVersion: v1
kind: Service
metadata:
  name: {{ include "your-chart-name.fullname" . }}
  labels:
    {{- include "your-chart-name.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "your-chart-name.name" . }}
    release: {{ .Release.Name }}