apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: wordpress-alerts
  labels:
    app: wordpress
spec:
  groups:
    - name: wordpress.rules
      rules:
        - alert: HighPodCPUUtilization
          expr: sum(rate(container_cpu_usage_seconds_total{namespace="default", pod=~"wordpress-.*"}[5m])) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace="default", pod=~"wordpress-.*"}) by (pod) > 0.8
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High CPU utilization detected on pod {{ $labels.pod }}"
            description: "Pod {{ $labels.pod }} is using more than 80% of its CPU limit."

        - alert: HighNginx5xxErrors
          expr: sum(rate(nginx_http_requests_total{status=~"5..", namespace="default", pod=~"nginx-.*"}[5m])) by (pod) > 5
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High 5xx error rate detected on Nginx pod {{ $labels.pod }}"
            description: "Nginx pod {{ $labels.pod }} has more than 5 5xx errors in the last 5 minutes."

        - alert: TotalRequestCount
          expr: sum(rate(nginx_http_requests_total{namespace="default", pod=~"nginx-.*"}[5m])) by (pod) > 100
          for: 5m
          labels:
            severity: info
          annotations:
            summary: "High request count on Nginx pod {{ $labels.pod }}"
            description: "Nginx pod {{ $labels.pod }} has received more than 100 requests in the last 5 minutes."